### ISSUE TITLE
Issue With Connector Plugin

### ISSUE THREAD

**Issue by BastiaanSahetapy** [ServerSelectorX/Connector-Addons#3]
I use the latest versions of every plugin, Selector plugin aswell of the connector.
At some times, my connector says the servers are offline, but in bungeecord they are online.

**Comment by Derkades** [comment]
Issues related to the connector plugin should be created here: https://github.com/ServerSelectorX/ServerSelectorX-Connector/issues

Anyway, I am rewriting the connector plugin so this should be fixed soon.
